# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run the test"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload test build to Testfairy"
  lane :upload_testfairy do
    testfairy(
      api_key: ENV[TESTFAIRY_API_KEY],
      apk: "../build/app/outputs/bundle/release/app-release.aab",
      comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
    )
  end
end
